CREATE TABLE IF NOT EXISTS template (
    id int(10) unsigned NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    datamapping JSON NOT NULL,
    filepath VARCHAR(255) NOT NULL,
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;