INSERT INTO `access` (`id`, `name`, `reference_key`) VALUES
(1, 'template_GET', NULL),
(2, 'template_CREATE', NULL),
(3, 'template_UPDATE', NULL),
(4, 'template_DELETE', NULL),
(5, 'temple_GET', 'id'),
(6, 'temple_CREATE', ''),
(7, 'temple_UPDATE', 'id'),
(8, 'temple_DELETE', 'id'),
(9, 'service_type_GET', NULL),
(10, 'service_type_CREATE', NULL),
(11, 'service_type_UPDATE', NULL),
(12, 'service_type_DELETE', NULL),
(13, 'service_GET', NULL),
(14, 'service_CREATE', NULL),
(15, 'service_UPDATE', NULL),
(16, 'service_DELETE', NULL);